- name: Deploy Scientific Calculator
  hosts: localhost

  tasks:
    - name: Pull Docker Image
      command: docker pull prabhav49/scientific-calculator:latest

    - name: Run Scientific Calculator Container
      command: docker run --rm prabhav49/scientific-calculator:latest 1
