- name: Deploy Scientific Calculator
  hosts: localhost
  become: false

  tasks:
    - name: Pull Docker Image
      command: docker pull prabhav49/scientific-calculator:latest

    - name: Run Scientific Calculator Container
      command: docker run -d prabhav49/scientific-calculator:latest 1 2 4

